spring:
  profiles:
    #激活指定环境   dev - 开发环境  prod - 生产环境
    active: prod
server:
  servlet:
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isdelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
---
#开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3307/novices
server:
  port: 8080
knife4j:
  enable: true
  openapi:
    title: "用户管理系统接口文档"
    description: "用户管理系统接口文档"
    email: novices666@gmail.com
    concat: Novices
    url: https://github.com/Novices666/
    version: v4.0
    group:
      user-control:
        group-name: 用户管理
        api-rule: package
        api-rule-resources:
          - cc.novices.usercontrol.controller

---
#生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xxxxxxxxx
    url: jdbc:mysql://localhost:3306/xxxxxxxxxxxx?characterEncoding=utf-8&serverTimezone=UTC&&useSSL=false
server:
  port: 8081
knife4j:
  enable: false